import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Sora } from "next/font/google";
import "./globals.css";
import { ResumeProvider } from "@/context/ResumeContext";
import { ModalProvider } from "@/components/ui/resumeModal/animated-modal";
import { ToastContainer } from "react-toastify";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakarta.variable} ${sora.variable}  antialiased`}>
        <ResumeProvider>
          <ModalProvider>
            {children}
            <ToastContainer position="top-center" theme="dark" />
          </ModalProvider>
        </ResumeProvider>
      </body>
    </html>
  );
}
